---
version: "3.8"
services:
  webserver:
    build: .
    volumes:
      - "./dev-knot/public:/usr/share/nginx/html"
    ports:
      - "80:80"
      - "443:443"
    image: ${COMMIT_IMAGE:-h4ndzdatm0ld/dev-knot-blog:latest}
