---
version: "3.8"
services:
  webserver:
    build: "."
    # volumes:
    # - "./default.conf:/etc/nginx/conf.d/default.conf"
    #   - "./dev-knot/public:/usr/share/nginx/html"
    # - ./nginx/conf/:/etc/nginx/conf.d/:ro
    # - ./certbot/www:/var/www/certbot/:ro
    ports:
      - "8000:80"
      - "443:443"
    image: ${COMMIT_IMAGE:-h4ndzdatm0ld/dev-knot-blog:latest}
    restart: "always"
    environment:
      LETSENCRYPT_DOMAIN: ${LETSENCRYPT_DOMAIN:-dev-knot.com}"
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL:-hugotinoco@icloud.com}"
  terraform:
    working_dir: "/usr/src/app"
    image: "hashicorp/terraform:latest"
    volumes:
      - "./terraform/:/usr/src/app/"
    environment:
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
      AWS_REGION: "${AWS_REGION}"
  # certbot:
  #   environment:
  #     LETSENCRYPT_DOMAIN: ${LETSENCRYPT_DOMAIN:-dev-knot.com}"
  #     LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL:-hugotinoco@icloud.com}"
  #   image: "certbot/certbot:latest"
  #   volumes:
  #     - "./certbot/conf:/etc/letsencrypt"
  #     - "./certbot/www:/var/www/certbot"
  #   command: "certonly --webroot -w /var/www/certbot --force-renewal --email ${LETSENCRYPT_EMAIL} -d ${LETSENCRYPT_DOMAIN} --agree-tos"
