---
version: "3.8"
services:
  terraform:
    working_dir: "/usr/src/app"
    image: "hashicorp/terraform:latest"
    volumes:
      - "./terraform/:/usr/src/app/"
    environment:
      TF_VAR_gh_access_token: "${TF_VAR_gh_access_token}"
      TF_TOKEN_app_terraform_io: "${TF_TOKEN_app_terraform_io}"
  blog:
    build: "."
    container_name: "blog"
    working_dir: "/usr/src/app"
    command: "serve --minify --config ./config.toml -e production"
    volumes:
      - "./dev-knot:/usr/src/app"
    ports:
      - "8080:1313"
    image: ${IMAGE_TAG:-h4ndzdatm0ld/dev-knot-blog:latest}
    restart: "always"
