baseURL = "https://dev-knot.com"
languageCode = "en-us"
languageName = "English"
theme = "LoveIt"
description = "Welcome to Dev Knot Blog"
subtitle = "Dev Knot Blog"
defaultContentLanguage = "en"
defaultContentLanguageName = "English"

# Author config
[author]
  name = "Hugo Tinoco"
  email = "hugotinoco@icloud.com"
  link = "https://www.linkedin.com/in/hugo-tinoco/"
