---
name: "CI-Docker-Build"

on: # yamllint disable
  push:
    branches: ["*"] # TODO: (HUGO) Change to main after testing

jobs:
  build:
    name: "Publish to Docker Registry"
    runs-on: "ubuntu-20.04"
    steps:
      - uses: "actions/checkout@v2"

      - name: "Setup Hugo"
        uses: "peaceiris/actions-hugo@v2"
        with:
          hugo-version: "latest"
          extended: true

      - name: "Build"
        run: "hugo --minify --config ./dev-knot/config.toml"

      - uses: "docker/login-action@v1"
        with:
          username: "${{ secrets.DOCKERHUB_USERNAME }}"
          password: "${{ secrets.DOCKERHUB_TOKEN }}"

      - name: "Docker Compose Build"
        run: "docker-compose build"

      - name: "Docker Push"
        run: "docker push ${{ secrets.DOCKERHUB_USERNAME }}/dev-knot-blog:latest"
