---
name: "CI-Docker-Build"

on: # yamllint disable
  push:
    branches: ["*"]

jobs:
  build:
    name: "Publish to Docker Registry"
    runs-on: "ubuntu-20.04"
    steps:
      - uses: "actions/checkout@v2"
        with:
          submodules: "recursive"

      - name: "Setup Hugo"
        uses: "peaceiris/actions-hugo@v2"
        with:
          hugo-version: "latest"
          extended: true

      - name: "Build"
        run: "cd dev-knot && hugo --minify --config ./config.toml"

      - uses: "docker/login-action@v1"
        with:
          username: "${{ secrets.DOCKERHUB_USERNAME }}"
          password: "${{ secrets.DOCKERHUB_TOKEN }}"

      - name: "Docker Compose Build"
        run: "docker-compose build -f docker-compose-dev.yml"

      - name: "SET DEVELOP TAG"
        if: github.ref == 'refs/heads/develop'
        run: |
          echo "IMAGE_TAG=h4ndzdatm0ld/dev-knot-blog:develop" >> $GITHUB_ENV

      - name: "Docker Push"
        run: "docker push ${{ secrets.DOCKERHUB_USERNAME }}/dev-knot-blog:develop"
        if: github.ref == 'refs/heads/develop'

      - name: "SET LATEST TAG"
        if: github.ref == 'refs/heads/main'
        run: |
          echo "IMAGE_TAG=h4ndzdatm0ld/dev-knot-blog:latest" >> $GITHUB_ENV

      - name: "Docker Push"
        run: "docker push ${{ secrets.DOCKERHUB_USERNAME }}/dev-knot-blog:latest"
        if: github.ref == 'refs/heads/main'
